### ISSUE TITLE
figures with just paragraphs

### ISSUE THREAD

**Issue by pkra** [AmerMathSoc/texml#141]
jams 1005 https://github.com/AmerMathSoc/jams/pull/163 had something like 

```
\begin{figure}[H]
\textbf{Summary of notations}

paragraph 1

paragraph 2

paragraph 3
\end{figure}
```

This did not come out as paragraphs. While we fixed this temporarily at the source, it would be good to fix here eventually.

**Comment by davidmjones** [comment]
No, the markup you cite was my fault -- the original had a parbox inside an fbox and I was trying to simplify it to somthing palatable to texml, but I forgot that, for excellent reasons, par tags are suppressed inside figure environments.  There might yet be a case where we actually do need paragraphs inside a figure, but this isn't an example.

**Comment by pkra** [comment]
Ah, ok. Thanks for clarifying.
