### ISSUE TITLE
problematic formatting in kwd

### ISSUE THREAD

**Issue by pkra** [AmerMathSoc/texml#156]
It seems texml "prettifies" inline-formula markup if it's at the beginning of a keyword.

This causes extraneous whitespace downstream.

E.g.,

```tex
\keywords{$p$-Laplacian, best $N$-term approximation}
```

turns into 

```xml
  <kwd-group kwd-group-type="author">
        <kwd>
          <inline-formula content-type="math/tex">
            <tex-math>p</tex-math>
          </inline-formula>-Laplacian</kwd>
        <kwd>best <inline-formula content-type="math/tex"><tex-math>N</tex-math></inline-formula>-term approximation</kwd>
      </kwd-group>
```

**Comment by pkra** [comment]
This might be more generally about "kwd starting with an element". 

E.g., `\rom{R}$_\eta$`gives

```
  <kwd>
          <roman>R</roman>
          <inline-formula content-type="math/tex">
            <tex-math>_\eta </tex-math>
          </inline-formula>
        </kwd>
```

**Comment by pkra** [comment]
Looks like 43 publications are affected; a few others have keywords that are math-mode only.

**Comment by davidmjones** [comment]
I tweaked the whitespace handling in the XML pretty-printer, so it should stop doing this.
