### ISSUE TITLE
smash in math mode

### ISSUE THREAD

**Issue by pkra** [AmerMathSoc/texml#162]
I was trying to fix the downstream problem I documented at https://github.com/mathjax/MathJax/issues/2863.

But I'm unable to get smash in the output for a testcase. E.g., `$\smash{\overrightarrow{OP}}$` gives me 

```xml
<inline-formula content-type="math/tex"><tex-math>\mathchoice{<inline-formula content-type="math/tex"><tex-math>\displaystyle {\overrightarrow {OP}}</tex-math></inline-formula>}{<inline-formula content-type="math/tex"><tex-math>\textstyle {\overrightarrow {OP}}</tex-math></inline-formula>}{<inline-formula content-type="math/tex"><tex-math>\scriptstyle {\overrightarrow {OP}}</tex-math></inline-formula>}{<inline-formula content-type="math/tex"><tex-math>\scriptscriptstyle {\overrightarrow {OP}}</tex-math></inline-formula>}</tex-math></inline-formula>
```

Which seems both unnecessary and problematic (since mathchoice is followed by xml markup).

**Comment by davidmjones** [comment]
it looks like MathJax implements `\smash`, so I guess the right thing to do is pass it through unmolested in math mode and strip it from text mode?

**Comment by pkra** [comment]
Yes, MathJax can do `\smash` in math mode. 

(What I couldn't figure out is that texml must have passed it through in the past - we ran into this with an MCL and again with a GSM more recently.)

**Comment by pkra** [comment]
I believe smash is passed through now.
