### ISSUE TITLE
cross-references in svg output

### ISSUE THREAD

**Issue by pkra** [AmerMathSoc/texml#177]
Can we make progress on resolving at least some cross-references from content that's SVG-ified?

**Comment by davidmjones** [comment]
@pkra What needs to be done?

**Comment by pkra** [comment]
This came up in FBF discussions. I'd like to work out what it would take to get citations and cross-references to work in texml-generated SVGs. AFAIU the current setup is extracting contents so it won't lend itself easily to doing so - but maybe there's a way? 

There's also the question of styling for the resulting links in the SVGs but that's potentially less difficult.

And of course downstream would need to adapt -- but this matches plans around inlining SVGs downstream (cf. also #166), in which case those references would actually work.
