### ISSUE TITLE
calrsfs and mathrsfs packages: `\mathscr` vs. `\mathcal`

### ISSUE THREAD

**Issue by davidmjones** [AmerMathSoc/texml#180]
Currently I'm mapping `\mathscr` and `\mathrsfs` to `\mathcal`, but I think they should both be `\mathscr`.  This could be a problem if an author is using `\mathcal` and `\mathscr` for contrast instead of just using `\mathsrc` instead of `\mathcal`.  I need to investigate to see how many papers this affects.

I should also review eucal.pm.

**Comment by pkra** [comment]
mathscr works with MathJax out of the box,  https://github.com/mathjax/MathJax-src/blob/8565f9da973238e4c9571a86a4bcb281b1d98d9b/ts/input/tex/base/BaseMappings.ts#L423

**Comment by davidmjones** [comment]
> mathscr works with MathJax out of the box,

Yes, I know.  That's not the issue.

**Comment by davidmjones** [comment]
@pkra It's hard to tell how many papers (if any) are affected by this, because `\mathscr` was defined and redefined in too many places.  I think `texml` is now handling it consistently and correctly.  The next time we regenerate everything, we might see some occurrences of `\mathcal` change to `\mathscr`, but this will be a bug fix.
