### ISSUE TITLE
toc: indicate entry (target's) type

### ISSUE THREAD

**Issue by pkra** [AmerMathSoc/texml#184]
For presenting the TOC downstream, it would be useful to know the type of an entry's target, e.g., part, chapter, section. 

Could this be exposed via texml?

**Comment by pkra** [comment]
@davidmjones I don't see a commit on the repository. Could you point me to where I can see what we need to handle downstream?

**Comment by davidmjones** [comment]
Sorry, I hadn't pushed yet.  I just did.  The only change is that I now copy the "specific-use" attribute from the target element to the toc-entry element.

________________________________
