### ISSUE TITLE
When are secheading elements created?

### ISSUE THREAD

**Issue by pkra** [AmerMathSoc/texml#194]
I couldn't find any reference in the code. 

In particular, I'm wondering what the sectioning situation around secheading is like. 

Is it correct that they are created only if texml does not/cannot create a `sec` element?

**Comment by davidmjones** [comment]
It's in TeX::Interpreter::FMT::latex in a slightly obfuscated form:

    \def\XML@section@tag{sec}
    
    \def\start@XML@section#1#2#3#4{
        \par
        \stepXMLid
        \begingroup
            \ifinXMLelement{statement}%
                \startXMLelement{\XML@section@tag heading}%
            \else
                \@pop@sectionstack{#2}%
                \startXMLelement{\XML@section@tag}%
            \fi

Currently `texml` only creates a secheading when a section command is nested inside a `<statement>`.

**Comment by pkra** [comment]
Thanks for clarifying!
