### ISSUE TITLE
Updates to book metadata

### ISSUE THREAD

**Issue by davidmjones** [AmerMathSoc/texml#195]
We are finally starting to send metadata to discovery services, etc., as BITS and JATS.  Since we will be sending full-text XML files to some of them, we need to harmonize the metadata generated by texml with the metadata generated by the metadata-only system.

Changes to both article and book metadata:

* Delete superfluous `date-type` attribute from the `<pub-date>` element.
* Currently the PDF `<self-uri>` element looks like `<self-uri xlink:href="URI"/>`.  It will now be `<self-uri xlink:href="URI">URI<self-uri>`.

Changes to book metadata:

* Add a `collection-type` attribute to the `<colletion-meta>` element
  with value "book series".
* Add a `<self-uri>` element for the series URL after the `<publisher>` element.
* Add an LCCN `<book-id>` to the `<book-meta>` element.
* Add a `<pub-date>` element after the `<history>`.
* Add a `<book-volume-id>` element after the `<book-volume-number>`
* Add abstract and PDF `<self-uri>` elements after the permissions.
* Remove the `<issn>` element from the `<book-meta>` element since it duplicates the one in the `<collection-meta>`.

That's all for now.  I might add more when I work through more examples.

**Comment by pkra** [comment]
Thanks for the details. This sounds like downstream won't have to do anything for now - it will simply ignore the new markup (and find the issn regardless). If you want to preserve some of this data downstream, we can file issues downstream as needed.

**Comment by davidmjones** [comment]
@pkra The only substantive addition is the LCCN, which is already in the CIP pages.  So unless there is a place to plug that into the EPUB metadata, I don't think there's anything to be done.

I'll install these changes.

**Comment by pkra** [comment]
I think this can be closed. texml-to-html now preserves LCCN, too.
