### ISSUE TITLE
Add `<license/>` and `<ali:free_to_read/>` tags

### ISSUE THREAD

**Issue by davidmjones** [AmerMathSoc/texml#216]
@pkra I'm going to add `<license/>` and `<ali:free_to_read/>` tags at the end of the `<permissions/>` element, after the copyright.  Hopefully this won't affect your code, but let me know if you need me to hold off on this change.

**Comment by pkra** [comment]
texml-to-html works by allow-list only, so unknown elements will be ignored/stripped. Let me know if we need to do something with these.

**Comment by davidmjones** [comment]
@pkra Thanks.  I don't think you need to do anything with the information. It's just there to make the license more explicit for aggregators.

**Comment by davidmjones** [comment]
Implemented.
