### ISSUE TITLE
Identify corrigenda and the article they correct

### ISSUE THREAD

**Issue by pkra** [AmerMathSoc/texml#38]
Pointed out by RVR on https://github.com/AmerMathSoc/ams-doc-sources/pull/1846#issuecomment-516397638:

> I'm wondering if there will be a link to the original article on the Article Info tab, like on the abstract page.

**Comment by pkra** [comment]
While this was indeed rolled out, the more relevant scenario still lacks a use case -- we have not yet had an article that later had a correction.

**Comment by davidmjones** [comment]
> While this was indeed rolled out, the more relevant scenario still lacks a use case -- we have not yet had an article that later had a correction.

You'll be very happy to see jams1025 then.

**Comment by pkra** [comment]
Excellent timing :smile: I've filed issues downstream.
