### ISSUE TITLE
Realizing algorithms as markup

### ISSUE THREAD

**Issue by pkra** [AmerMathSoc/texml#40]
Currently algorithm displays are rendered as SVG. This leads to various smaller and greater issues (typographic consistency, complications with reference resolution, accessibility).

It does not appear difficult to realize common layouts for algorithm displays in CSS.

Some questions (to be revised / expanded): 

* which packages should we support?
  * Algorithm2e, Algorithmic, and Listings seem the most popular packages, cf. https://www.overleaf.com/learn/latex/algorithms.
* do the various LaTeX algorithm packages provide suitable command structures for such a conversion?
* does real life content create extra problems?
* is there a reasonable encoding in jats/bits XML document or would we go straigth for HTML (as with tables)?
  * if creating HTML is the path, do we create HTML to CSS specifications or algorithmdisplay-specific CSS alongside the HTML (as with tables)?

**Comment by pkra** [comment]
Would it be possible to push a branch that has the working code?

**Comment by pkra** [comment]
Random note: algorithm.pdf is out of date.

**Comment by pkra** [comment]
random note: the print "Hello World" has proper open/closing quotation marks when the PDF doesn't.

**Comment by pkra** [comment]
Some questions based on the current output in algorithmic.xml

* The first 4 comments are not part of "their" line. All other comments appear within `alg:line`. Shouldn't all of them be the same (within their line)?
* `alg:until` is missing its `<bold>until</bold>` - just a simple oversight?

**Comment by pkra** [comment]
Would it make sense to have an attribute to indicate the "spans across the linenumber" behavior that `alg:require` and `alg:ensure` have? Otherwise, downstream will need to keep an allowlist which is more brittle.

**Comment by pkra** [comment]
I was trying out `\LoadPackage{Algorithmic}` which worked fine on the test file.

But downstream, I ran into an issue. I had chosen the test from mcom3363 but used the original source -- including the algorithm environment. 

```tex
\begin{algorithm}\caption{Kaltofen--Shoup EDF for extension fields}
	\label{alg:ks}
	\begin{algorithmic}[1]
		\REQUIRE A polynomial $h$  with irreducible factors of degree $d$ over $k=\mathbb{F}_q[X]/f(X)$.
		\ENSURE An irreducible factor of $h$ over $k$.
		\STATE If $\deg h = d$ return $h$.
		\STATE Take a random polynomial $a_0\in k[Z]$ of degree less than $\deg h$,
		\STATE\label{alg:ks-pseudotrace} Compute $a_1
		\leftarrow \sum_{i=0}^{md-1} a_0^{q^i} \mod h$,
		\IF{$q$ is an even power $q=2^e$}
		\STATE\label{alg:ks:even} Compute $a_2 \leftarrow
		\sum_{i=0}^{e-1} a_1^{2^i}\mod h$
		\ELSE \COMMENT{(Not an even power)}
		\STATE\label{alg:ks:odd} Compute $a_2 \leftarrow a_1^{(q-1)/2}\mod h$
		\ENDIF
		\STATE\label{alg:ks:gcd} Compute $h_0\leftarrow\gcd(a_2,h)$ and
		$h_1\leftarrow\gcd(a_2-1,h)$ and $h_{-1}\leftarrow h/(h_0h_1)$,
		\STATE Apply recursively to the smallest non-constant polynomial among
		$h_0,h_1,h_{-1}$.
	\end{algorithmic}
\end{algorithm}
```

This crashed both the test here and downstream.

**Comment by pkra** [comment]
Here's the full error

```
Applying XSL stylesheet '..../texml/bin/../lib/xsl/bits.xsl'
Transcript written on test01.log.

not well-formed (invalid token) at line 558, column 43, byte 127725:
                <label>Algorithm 3.3</label>
                <p content-type="noindent"><label>name </label>Kaltofen–Shoup [snip]
==========================================^
              </statement>
 at /usr/lib/x86_64-linux-gnu/perl5/5.32/XML/Parser.pm line 187.
 at /usr/bin/xml_pp line 51.
 at /usr/bin/xml_pp line 51.
```

The second label seems to be the problem -- it's actually `<label>name </label>` in the output.

**Comment by pkra** [comment]
Oh, actually the entire markup is alg:* markup is missing.

**Comment by pkra** [comment]
On a side note, I noticed in that first mcom paper and now that texml produces statement. I think fig is better (we've also treated algorithms as figures in the past).

**Comment by pkra** [comment]
This is being rolled out (slowly)

**Comment by davidmjones** [comment]
> Some questions based on the current output in algorithmic.xml
> 
>     * The first 4 comments are not part of "their" line. All other comments appear within `alg:line`. Shouldn't all of them be the same (within their line)?

There are two different ways of markup up comments which were being treated differently.  I've moved `\COMMENT` comments inside their `<line>` element.  Hopefully.

>     * `alg:until` is missing its `<bold>until</bold>` - just a simple oversight?

Yes.  Fixed now.

**Comment by pkra** [comment]
Documentation added.
