### ISSUE TITLE
avoid invalid HTML table markup / alternative approaches to table css

### ISSUE THREAD

**Issue by pkra** [AmerMathSoc/texml#67]
texml currently generates CSS using nth-child selectors to target individual rows and cells. 

In the context of colspan and rowspan, this forced us to add hidden TD elements so that nth-child calculations would fit, cf. https://github.com/AmerMathSoc/texml/issues/45.

Unfortunately, this leads to invalid markup ([html spec](https://html.spec.whatwg.org/multipage/tables.html#forming-a-table) "If there exists a row or column in the table containing only slots that do not have a cell anchored to them, then this is a table model error.")

One solution would be to modify nth-child calculations (taking colspan and rowspan into account) to avoid this invalid markup. 

Alternatively, texml could consider generating "functional CSS" instead, i.e., generate utility classes and add the class names to the table elements. Given the analysis in https://github.com/AmerMathSoc/texml/issues/45#issuecomment-585320408 this seems useful since the variations among styles seems limited. At least, it should be simple to do for borders (which is enough to fix  the invalid markup). 
 
I made a first example with a table in mcom3377 at  https://codepen.io/pkra/pen/cc864b02c372e7451ad407dd7fffdd47.

**Comment by davidmjones** [comment]
@pkra Can you take a look at the various table-related test files in the atomic-table-css branch, especially tabular.xml and colortbl.xml?  Others are arydshln, booktabs, hhline and multirowcell, which still suffers from the hidden cell counting bug.

**Comment by davidmjones** [comment]
Also multicolumn and multirow.

**Comment by pkra** [comment]
Very exciting!

* tabular
  * table 3, 4: the hfill has no effect. Could be interpreted as right-align (or perhaps`float:right` which I'd like to avoid)
  * table 4: Should the `5in` have an effect?
  * table 7,8 : B-line is missing an effect for [3\jot] (I think padding-bottom for the cells?)
  * table 8:  `l@{X} ` gives an X in the column but it's not in the right (visual) position
    * needs more info as I'm not entirely sure how this works internally (in TeX). Maybe these need to be their own column or they may need something like `float:right` (on a wrapping element or as ::after).
* colortbl
  * tex source is missing xcolor, I think
  * row 1, 4, 5: filler cells at end
  * row 2: last cell is green (PDF: gray) because it gets a class derived from the table-level rowcolor, overriding the class on the parent row (derived from row-level rowcolor)
    * it will probably avoid headaches if all row color is applied on the cell level
  * row 3,4,5: cmyk to rgb comes out a too dark -- I get `#264059` on a conversion tool which seems closer to the PDF
  * row 7: the red cell with 2 padding-left does not match PDF (not sure why the PDF cell looks this way)
* arydshln -- looks good (except for the limitation noted in the source)
* booktabs
  * css file had old output and didn't change when I ran texml
* hline
  * random note: dumping all tables into a single HTML file for review gave me a clash of css for these two tables
  * table1: 
    * this can't (sensibly) be done with CSS, I think (i.e., without completely different markup or using the CSS paint API - which lacks support). 
    * The double border lines come out quite differently across browsers; it's not great but good enough for now
* multirowcell
  * table 1 looks good
  * table 2: there's a difference in how HTML spreads out the columns across the colspan. I don't see any css so this is probably core table layout.
* multicolumn: looks ok
* multirow looks ok (except that table 2 won't work in PDF)

Phew, that took a lot longer than I expected.

**Comment by pkra** [comment]
> random note: dumping all tables into a single HTML file for review gave me a clash of css for these two tables

This seems to have been due to the old booktabs CSS. In any case, I would suggest a texml-related prefix to namespace the class names.

**Comment by pkra** [comment]
Final note: all tables appear to render the same on Blink, WebKit, Gecko engines.

**Comment by davidmjones** [comment]
> tabular 

> table 3, 4: the hfill has no effect. Could be interpreted as right-align (or perhapsfloat:right which I'd like to avoid) 

Won't fix; note added to tabular.tex.

> table 4: Should the 5in have an effect? 

Dunno.  Hasn't been needed so far.  Note added to tabular.tex

> table 7,8 : B-line is missing an effect for [3\jot] (I think padding-bottom for the cells?) 

Fixed.

> table 8: l@{X} gives an X in the column but it's not in the right (visual) position

Won't fix; added note.

> colortbl 
> tex source is missing xcolor, I think 

Hmm.  Not needed on my machine -- color is automatically loaded by colortbl and that's good enough.  But I'll add it.

> row 1, 4, 5: filler cells at end 

Ah.  I was under the misapprehension that I needed to keep the filler cells to make horizontal rules work.  I removed them.

> row 2: last cell is green (PDF: gray) because it gets a class derived from the table-level rowcolor, overriding the class on the parent row (derived from row-level rowcolor)

blech.  later.  maybe.

> it will probably avoid headaches if all row color is applied on the cell level 

Ok.

> row 3,4,5: cmyk to rgb comes out a too dark -- I get #264059 on a conversion tool which seems closer to the PDF 

Meh.  In practice, that color is too dark to be usable either way -- it was just a random example.  I replaced it by something lighter.  I went to a lot of trouble to get xcolor to do the color conversion for me.  I don't think there's anything to be gained by second guessing it -- color is weird.

> row 7: the red cell with 2 padding-left does not match PDF (not sure why the PDF cell looks this way) 

Not sure what you're referring to.

> arydshln -- looks good (except for the limitation noted in the source) 

> booktabs 

That was broken.  Fixed now.

> hline: The double border lines come out quite differently across browsers; it's not great but good enough for now 

I don't think we have any papers that use it (yet) -- I was just
trying to be thorough in the test file.

> multirowcell: table 2: there's a difference in how HTML spreads out the columns across the colspan. I don't see any css so this is probably core table layout. 

Interesting.  It looks like the browser is allocates the spanned columns equal shares of the width of the combined column.  Cf. the new third tables in multicolumn.tex and multirowcell.tex.

**Comment by davidmjones** [comment]
@pkra I think the hhline2 test file works correctly (except as noted in the LaTeX file) now too.

**Comment by pkra** [comment]
Awesome update (and rolling out! :rocket:).


### tabular

> >  table 7,8 : B-line is missing an effect for [3\jot] (I think padding-bottom for the cells?)
> Fixed.

I see that you solved the problem of TRs not allowing padding by moving that to the TDs. That's great (and generally is best as we discussed -- and the borders could also move down if you want TRs to be clean).

Something trivial I realized later: you could of course still put a class on the TR and then have `tr.pb > td { padding-bottom: ...}` in the stylesheet. Just in case we ever have a hard time 

### colortbl

> >    row 1, 4, 5: filler cells at end
> Ah. I was under the misapprehension that I needed to keep the filler cells to make horizontal rules work. I removed them.

Right. On the TR, the horizontal borders will be as long as the longest TR. For a partial border, put them on the relevant TDs.

> > row 2: last cell is green (PDF: gray) because it gets a class derived from the table-level rowcolor, overriding the class on the parent row (derived from row-level rowcolor)
> blech. later. maybe.

Quick fix should we ever need it: in the stylesheet change `.bc { background-color: #bfbfbf; }` to `.bc > td { background-color: #bfbfbf;}` -- the selector`.bc > td` has higher specificity than `.bc1` and thus "wins". 

(Though selector specificity can be gnarly and we should be careful to check if this matches how colortbl would resolve clashing colors).

>  > row 7: the red cell with 2 padding-left does not match PDF (not sure why the PDF cell looks this way)
> Not sure what you're referring to.

The `2` with red-background:

PDF has some left padding (compiled by me so maybe something's wrong on my system)>
![image](https://user-images.githubusercontent.com/426686/168035945-4d5942fa-62b1-465e-a3d9-7cff6ca67c33.png)

HTML does not

![image](https://user-images.githubusercontent.com/426686/168036063-c997f01c-76fc-4ba6-9003-d5b39790897d.png)

**Comment by pkra** [comment]
> @pkra I think the hhline2 test file works correctly (except as noted in the LaTeX file) now too.

If I understand the note in the TeX file correctly, a multicolumn won't come out flushed left but instead follow the column specifier says. 

If that's right, then I don't understand. Table 2

On the one hand `& \multicolumn{1}{p{4em}|}{C2} & \multicolumn{1}{p{4em}|}{C3}`

On the other, the HTML renders

![image](https://user-images.githubusercontent.com/426686/168056149-d9a3197b-31e0-4b9e-a510-152cce2dff21.png)

**Comment by davidmjones** [comment]
> I see that you solved the problem of TRs not allowing padding by moving that to the TDs. That's great (and generally is best as we discussed -- and the borders could also move down if you want TRs to be clean).

But wouldn't we then have the problem that if a particular row has missing cells, the rule won't extend all the way across the full row width?

**Comment by davidmjones** [comment]
> The 2 with red-background:

> PDF has some left padding (compiled by me so maybe something's wrong on my system)

That appears to be because \cellcolor does not ignore space after it.  This would be...difficult...to reproduce.

**Comment by davidmjones** [comment]
> > row 2: last cell is green (PDF: gray) because it gets a class derived from the table-level rowcolor, overriding the class on the parent row (derived from row-level rowcolor)

> blech. later. maybe.

I think I found an approach that preserves the correct precedence for color specifiers without screwing anything up.

**Comment by pkra** [comment]
> The problem is with multirow, not multicolumn. See the "C6, R1-3" cell in that same table.

Duh. Sorry. Thanks for clarifying.

> But wouldn't we then have the problem that if a particular row has missing cells, the rule won't extend all the way across the full row width?

Yes, of course. Sorry about that.

**Comment by pkra** [comment]
When running locally, I get some stray color markup in the output, e.g., `\rowcolor{gray!20}` leaves `gray!20` in the cell content. 

(I also get `  <p>color push rgb 0 0 0</p>` at the top of the document and there are other things that don't work in a my installation.)

**Comment by pkra** [comment]
> When running locally, I get some stray color markup in the output, e.g., \rowcolor{gray!20} leaves gray!20 in the cell content.

Oh, it's actually worse -- the rowcolor is actually lost. (I'm on the main branch btw -- I think we can delete the atomic-css one?)

**Comment by pkra** [comment]
Finally, I've lost a table border

![image](https://user-images.githubusercontent.com/426686/169482419-34dea883-c088-4552-96c3-5715a3fb5220.png)

**Comment by pkra** [comment]
> Finally, I've lost a table border

Ah, apparently, this is now matching TeX. Nice.

**Comment by pkra** [comment]
> > When running locally, I get some stray color markup in the output, e.g., \rowcolor{gray!20} leaves gray!20 in the cell content.
> 
> Oh, it's actually worse -- the rowcolor is actually lost. (I'm on the main branch btw -- I think we can delete the atomic-css one?)

Adding `\usepackage[table]{xcolor}` seems to have solved this for me.

**Comment by pkra** [comment]
This has been rolled out completely now. I don't think additional docs are needed.

Hooray!
