### ISSUE TITLE
Implement generic metadata

### ISSUE THREAD

**Issue by davidmjones** [AmerMathSoc/texml#84]
Most of the JATS/BITS `<front>` element comes from the AMS gentag files.  We should implement a backup system that uses what little data is available in the LaTeX file.

**Comment by davidmjones** [comment]
@pkra Have a look at tests/maketitle.tex in the latest push.

**Comment by pkra** [comment]
Very nice!

**Comment by pkra** [comment]
> Very nice!

Alas, maketitle.tex compiles fine but our "regular" test files don't. Maybe we can sort that out at our next F2F.

**Comment by pkra** [comment]
> Alas, maketitle.tex compiles fine but our "regular" test files don't.

maybe that's not appropriate anyway since our test files should be closer to production.

> Maybe we can sort that out at our next F2F.

But lot's of questions so it'd be great to find some time next week.

**Comment by davidmjones** [comment]
> But lot's of questions so it'd be great to find some time next week.

@pkra Sure.

One problem I know about is that if the test file contains \maketitle, the XML file now gets an xml-last-modified date, which causes the regression test to fail.  Is that what you ran into, or is there something else?

**Comment by pkra** [comment]
Texml now can do quite a bit (author, thanks, title) - but I think only the noti classes? 

Hopefully it'll be easy to expose this more generally (and the noti classes have a ton of useful stuff for section metadata, too).
